from .CRUD.web_crud import WebCRUDWrapper
from .deparment_crud import deparment
from  .user_crud import user
from .job_crud import job
from .collaborator_crud import collaborator
from .project_crud import project
from .assignment_crud import assignment
from .assignment_crud import CollaboratorNotInProject
from .project_collaborator import project_collaborator_obj
from .announcement_crud import announcement